version: '0.2'

volumes:
  postgres-data:
  backend-data:
  static_volume:
  media_volume:
networks:
  wsrtbackend:

services:
  wsrtbackend:
    image: trancezero/wsrtbackend:v0.9
    env_file: 
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn wsrtbackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - backend-data:/home/wsrtbackend
      - static_volume:/home/staticfiles
      - media_volume:/home/mediafiles
    ports:
      - ${DJANGO_PORT}:8000
    depends_on:
      - wsrtdb
    networks:
      - wsrtbackend
  wsrtdb:
    image: postgres:15
    env_file: 
      - .env.prod
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRE_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=${POSTGRE_HOST}
    ports:
      # port $POSTGRE_PORT for connection on local computer
      - ${POSTGRE_PORT}:5432
    networks:
      - wsrtbackend
  wsrtnginx:
    image: trancezero/wsrtnginx
    env_file: 
      - .env.prod
    build: ./wsrtnginx
    volumes:
      - static_volume:/home/staticfiles
      - media_volume:/home/mediafiles
    ports:
      # port for debugging nginx on local computer
      - ${NGINX_PORT}:80
    depends_on:
      - wsrtbackend
    networks:
      - wsrtbackend
