# Generated by Django 4.2 on 2024-11-07 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('expire_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('usage', models.CharField(choices=[('R', 'Register'), ('A', 'Authenticate'), ('F', 'Function')], default='A', max_length=1)),
                ('function', models.CharField(default='', max_length=255, null=True)),
                ('max_use', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=member.models.user_profile_path)),
                ('motto', models.CharField(blank=True, max_length=100, null=True)),
                ('reputation', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('social_link', models.URLField(blank=True, max_length=255, null=True)),
                ('credit_remains', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
