# Generated by Django 4.2 on 2024-11-07 03:53

from django.db import migrations, models
import jisho.models


class Migration(migrations.Migration):

    dependencies = [
        ('jisho', '0002_jisho_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jisho',
            name='csv_file',
            field=models.FileField(null=True, upload_to=jisho.models.Jisho_file_path),
        ),
    ]
