# Generated by Django 4.2 on 2024-11-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jisho', '0006_memrecord_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordvariant',
            name='is_one_to_one',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='memrecord',
            name='mode',
            field=models.CharField(choices=[('I', 'One-to-one'), ('O', 'One-to-many fuzzy matching'), ('M', 'Many-to-one fuzzy matching'), ('A', 'One-to-one exact matching'), ('E', 'One-to-many exact matching'), ('X', 'Many-to-many exact matching'), ('C', 'Contextual problem solving')], default='O', max_length=1),
        ),
    ]
