# Generated by Django 4.2 on 2024-11-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jisho', '0007_wordvariant_is_one_to_one_alter_memrecord_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordvariant',
            name='variant',
            field=models.CharField(default='None', max_length=64),
        ),
        migrations.AlterField(
            model_name='wordvariant',
            name='value',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
