# Generated by Django 4.2 on 2024-11-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jisho', '0008_wordvariant_variant_alter_wordvariant_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpair',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
